### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by emmanuel128** [phil-brown/droidQuery#20]
I have this exception while running this code 

``` java
           @Override
            public void onClick(View v) {
                Map map = (Map<String, String>) $.map(
                        $.entry("LoginEmail", LoginEmail.getText().toString()),
                        $.entry("LoginPassword", LoginPassword.getText().toString()));


            $.ajax(new AjaxOptions().context(MainActivity.this).type("POST").url(api + "/PostLogin")
                            .data(map).cache(false).success(new Function() {
                                @Override
                                public void invoke($ $, Object... user) {
                                    switch (user[0].toString()) {
                                        case "admin":
                                            Toast admin = Toast.makeText(getBaseContext(), "admin", Toast.LENGTH_SHORT);
                                            admin.show();
                                            break;
                                        case "business":
                                            Toast business = Toast.makeText(getBaseContext(), "business", Toast.LENGTH_SHORT);
                                            business.show();
                                            break;
                                        case "consumer":
                                            Toast consumer = Toast.makeText(getBaseContext(), "consumer", Toast.LENGTH_SHORT);
                                            consumer.show();
                                            break;
                                        default:
                                            Toast toast = Toast.makeText(getBaseContext(), "Error", Toast.LENGTH_SHORT);
                                            toast.show();
                                            break;
                                    }
                                }
                            })
            );
        }
```
```
> 05-07 21:42:47.913 17905-17905/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:42:47.917 17905-17905/test.droidquerytest E/droidQuery: Could not complete ajax task!
>                                                                  java.lang.NoClassDefFoundError: self.philbrown.droidQuery.AjaxTask
>                                                                      at self.philbrown.droidQuery.$.ajax($.java:4490)
>                                                                      at test.droidquerytest.MainActivity$1.onClick(MainActivity.java:53)
>                                                                      at android.view.View.performClick(View.java:4789)
>                                                                      at android.view.View$PerformClick.run(View.java:19881)
>                                                                      at android.os.Handler.handleCallback(Handler.java:739)
>                                                                      at android.os.Handler.dispatchMessage(Handler.java:95)
>                                                                      at android.os.Looper.loop(Looper.java:135)
>                                                                      at android.app.ActivityThread.main(ActivityThread.java:5294)
>                                                                      at java.lang.reflect.Method.invoke(Native Method)
>                                                                      at java.lang.reflect.Method.invoke(Method.java:372)
>                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
>                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)

with .debug(true)

> 05-07 21:55:23.605 31242-31345/test.droidquerytest D/OpenGLRenderer: Enabling debug mode 0
> 05-07 21:55:23.990 31242-31242/test.droidquerytest I/Timeline: Timeline: Activity_idle id: android.os.BinderProxy@239f6cb1 time:17166196
> 05-07 21:55:28.891 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
> 05-07 21:55:28.891 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
> 05-07 21:55:28.892 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.css.CSSSelector>
> 05-07 21:55:28.898 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:55:28.899 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:55:28.899 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:55:28.899 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:55:28.901 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
> 05-07 21:55:28.935 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$6>
> 05-07 21:55:28.935 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$6>
> 05-07 21:55:28.972 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$12>
> 05-07 21:55:28.972 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$12>
> 05-07 21:55:28.975 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$18>
> 05-07 21:55:28.975 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$18>
> 05-07 21:55:28.980 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$16>
> 05-07 21:55:28.980 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$16>
> 05-07 21:55:28.983 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$14>
> 05-07 21:55:28.984 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.$$14>
> 05-07 21:55:29.027 31242-31242/test.droidquerytest I/art: Rejecting re-init on previously-failed class java.lang.Class<self.philbrown.droidQuery.AjaxTask>
```
I have this on dependencies

> dependencies {
>     testCompile 'junit:junit:4.12'
>     compile 'com.android.support:design:23.3.0'
>     compile 'com.android.support:appcompat-v7:23.3.0'
>     compile fileTree(dir: 'libs', include: ['*.jar'])}

**Comment by mohanedmoh** [comment]
hello did you solved the issue ?? cause I'm having the same thing
